export const TYPES_AUTHORIZATIONS = {
    READ: 1,
    WRITE: 2
} as const;

export const NAMES_TYPES_AUTHORIZATIONS = {
    [TYPES_AUTHORIZATIONS['READ']]: 'LECTURA',
    [TYPES_AUTHORIZATIONS['WRITE']]: 'ESCRITURA'
};


export type Auth = typeof TYPES_AUTHORIZATIONS[keyof typeof TYPES_AUTHORIZATIONS];

export const AUTH_OPTIONS = [
    {
        id: TYPES_AUTHORIZATIONS.READ,
        label: NAMES_TYPES_AUTHORIZATIONS[TYPES_AUTHORIZATIONS.READ]
    },
    {
        id: TYPES_AUTHORIZATIONS.WRITE,
        label: NAMES_TYPES_AUTHORIZATIONS[TYPES_AUTHORIZATIONS.WRITE]
    }
]